import { expect, test } from '@playwright/test';

const enter = '[data-life-enter]';
const exit = '[data-life-exit]';
const themes = '[data-theme-toggle]';

// Media verification uses a synthetic device, never the operator's microphone.
test.use({ launchOptions: { args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] } });

test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => {
        localStorage.setItem('otsugua.theme.preference', 'dark');
        localStorage.setItem('otsugua.locale.preference', 'en');
    });
});

test('entry preserves the document, world and layout; exit restores scroll and focus', async ({ page }) => {
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.goto('/');
    await page.evaluate(() => document.fonts.ready);
    await page.locator('.life-background').waitFor();
    await page.waitForTimeout(100);
    await page.evaluate(() => {
        (window as any).originalCanvas = document.querySelector('.life-background');
        (window as any).originalPixels = (document.querySelector('.life-background') as HTMLCanvasElement).toDataURL();
    });
    const height = await page.evaluate(() => document.documentElement.scrollHeight);
    await page.locator(enter).click();
    const position = await page.evaluate(() => scrollY);
    await expect(page.locator('html')).toHaveClass(/life-immersed/);
    await expect(page.locator('.life-background')).toHaveCSS('--life-reveal', '1');
    await expect(page.locator('.otsugua-page > main')).toHaveJSProperty('inert', true);
    await expect(page.locator('[data-home-header]')).toHaveJSProperty('inert', true);
    await expect(page.locator(themes)).toHaveJSProperty('inert', false);
    expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBe(height);
    await page.evaluate(() => window.scrollTo({ top: 700, behavior: 'instant' }));
    await expect.poll(() => page.evaluate(() => scrollY)).toBe(700);
    await page.locator(exit).click({ position: { x: 15, y: 100 } });
    await expect(page.locator('html')).not.toHaveClass(/life-immersed/);
    await expect.poll(() => page.evaluate(() => scrollY)).toBe(position);
    await expect(page.locator(enter)).toBeFocused();
    await expect(page.locator('.otsugua-page > main')).toHaveJSProperty('inert', false);
    expect(await page.evaluate(() => (window as any).originalCanvas === document.querySelector('.life-background'))).toBe(true);
    // The reduced-motion board must not be regenerated by either transition.
    await expect.poll(() => page.locator('.life-background').evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL()))
        .toBe(await page.evaluate(() => (window as any).originalPixels));
});

test('entry reveals controls for five seconds, and scrolling restarts their timer', async ({ page }) => {
    await page.clock.install();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.goto('/');
    await page.locator(enter).click();
    await expect(page.locator(themes)).toHaveCSS('opacity', '1');
    await expect(page.locator('[data-life-speed]')).toBeVisible();
    await page.clock.runFor(4900);
    await expect(page.locator(themes)).toHaveJSProperty('inert', false);
    await page.clock.runFor(101);
    await expect(page.locator(themes)).toHaveJSProperty('inert', true);
    await expect(page.locator(themes)).toHaveCSS('opacity', '0');
    await page.keyboard.press('Escape');
    await page.locator(enter).click();
    await expect(page.locator(themes)).toHaveCSS('opacity', '1');
    await expect(page.locator(themes)).toHaveJSProperty('inert', false);
    await page.evaluate(() => window.dispatchEvent(new WheelEvent('wheel', { deltaY: -30 })));
    await expect(page.locator(themes)).toHaveJSProperty('inert', false);
    await page.clock.runFor(4900);
    await expect(page.locator(themes)).toHaveCSS('opacity', '1');
    await page.evaluate(() => window.dispatchEvent(new WheelEvent('wheel', { deltaY: -30 })));
    await page.clock.runFor(4900);
    await expect(page.locator(themes)).toHaveCSS('opacity', '1');
    await page.clock.runFor(101);
    await expect(page.locator(themes)).toHaveJSProperty('inert', true);
    await expect(page.locator(themes)).toHaveCSS('opacity', '0');
});

test('mobile theme options stay vertically centered when selected, hovered or focused', async ({ page, isMobile }) => {
    test.skip(!isMobile, 'Mobile pill alignment');
    await page.goto('/');
    for (const immersed of [false, true]) {
        if (immersed) await page.locator(enter).click();
        for (const theme of ['system', 'dark', 'light']) {
            const button = page.locator(`[data-theme-option="${theme}"]`);
            await button.click();
            await button.press('ArrowRight'); // Exercise keyboard focus styling too.
            await expect.poll(() => button.evaluate(element => {
                const pill = element.closest('[data-theme-toggle]')!.getBoundingClientRect();
                const option = element.getBoundingClientRect();
                return Math.abs((option.top - pill.top) - (pill.bottom - option.bottom));
            })).toBeLessThan(0.02);
        }
    }
});

test('themes remain usable without exiting; keyboard focus survives the timer', async ({ page }) => {
    await page.clock.install();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.goto('/');
    await page.locator(enter).focus();
    await page.keyboard.press('Enter');
    await page.keyboard.press('Tab');
    await expect(page.locator('[data-theme-option="dark"]')).toBeFocused();
    await page.clock.runFor(6000);
    await expect(page.locator(themes)).toHaveJSProperty('inert', false);
    await page.keyboard.press('Tab');
    await page.keyboard.press('Enter');
    await expect(page.locator('html')).toHaveAttribute('data-theme-effective', 'light');
    await expect(page.locator('html')).toHaveClass(/life-immersed/);
    await expect(page.locator('.life-background')).toHaveCSS('--life-reveal', '1');
    await page.keyboard.press('Escape');
    await expect(page.locator(enter)).toBeFocused();
    await expect(page.locator('html')).not.toHaveClass(/life-immersed/);
    await expect(page.locator(themes)).toHaveJSProperty('inert', false);
});

test('the fade is reversible, with no hidden link activation or persistent immersive state', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/');
    await page.locator(enter).click();
    await page.keyboard.press('Escape');
    await expect(page.locator('.otsugua-page > main')).toHaveCSS('opacity', '1');
    await page.locator(enter).click();
    await expect(page.locator('.otsugua-page > main')).toHaveCSS('opacity', '0');
    await expect(page.locator('.life-background')).toHaveCSS('--life-reveal', '1');
    await page.locator(exit).click({ position: { x: 100, y: 100 } });
    expect(new URL(page.url()).hash).toBe('');
    await expect(page.locator('.otsugua-page > main')).toHaveCSS('opacity', '1');
    await page.locator(enter).click();
    await page.reload();
    await expect(page.locator('html')).not.toHaveClass(/life-immersed/);
    await expect(page.locator(exit)).toBeHidden();
    expect(errors).toEqual([]);
});

test('a real touch swipe scrolls the world and reveals controls without exiting', async ({ page, isMobile }) => {
    test.skip(!isMobile, 'Touch device contract');
    await page.goto('/');
    await page.locator(enter).tap();
    const cdp = await page.context().newCDPSession(page);
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 120, y: 620 }] });
    for (const y of [590, 530, 460, 390, 320]) {
        await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 120, y }] });
        await page.waitForTimeout(35);
    }
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(0);
    await expect(page.locator('html')).toHaveClass(/life-immersed/);
    await expect(page.locator(themes)).toHaveJSProperty('inert', false);
    await page.waitForTimeout(600);
    await page.touchscreen.tap(150, 250);
    await expect(page.locator('html')).not.toHaveClass(/life-immersed/);
});

test('a pointer-selected theme still fades away after five seconds', async ({ page }) => {
    await page.clock.install();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.goto('/');
    await page.locator(enter).click();
    await page.evaluate(() => window.dispatchEvent(new WheelEvent('wheel', { deltaY: -30 })));
    await page.locator('[data-theme-option="light"]').click();
    await expect(page.locator('html')).toHaveClass(/life-immersed/);
    await expect(page.locator('html')).toHaveAttribute('data-theme-effective', 'light');
    await page.clock.runFor(5100);
    await expect(page.locator(themes)).toHaveJSProperty('inert', true);
    await page.clock.runFor(1000);
    await expect(page.locator(themes)).toHaveCSS('opacity', '0');
});

for (const theme of ['light', 'dark']) {
    test(`revealing the field keeps the normal ${theme} palette`, async ({ page }) => {
        await page.emulateMedia({ reducedMotion: 'reduce' });
        await page.goto('/');
        await page.locator(`[data-theme-option="${theme}"]`).click();
        const palette = () => page.evaluate(() => {
            const canvas = getComputedStyle(document.querySelector('.life-background')!);
            return { cells: canvas.color, intensity: canvas.opacity, canvas: canvas.backgroundColor,
                backdrop: getComputedStyle(document.body).backgroundImage };
        });
        const normal = await palette();
        await page.locator(enter).click();
        await expect(page.locator('.life-background')).toHaveCSS('--life-reveal', '1');
        expect(await palette()).toEqual(normal);
        await page.keyboard.press('Escape');
        expect(await palette()).toEqual(normal);
    });
}

test('entering immersion closes Djinn rather than hiding an active session', async ({ page }) => {
    await page.goto('/');
    await page.locator('[data-djinn-keyboard]').click();
    await expect(page.locator('[data-djinn-response]')).toBeVisible();
    await page.locator(enter).focus();
    await page.keyboard.press('Enter');
    await expect(page.locator('[data-djinn-response]')).toBeHidden();
    await expect(page.locator('[data-djinn-control]')).toHaveAttribute('data-state', 'idle');
    await expect(page.locator('html')).not.toHaveClass(/djinn-open/);
});

test.describe('active microphone safety', () => {
    test('keyboard entry ends live capture and the mocked voice session', async ({ page }) => {
        let ended = false;
        await page.route(/https:\/\/djinn-voice\.test\//, route => route.fulfill({
            json: route.request().url().endsWith('/health')
                ? { demo: true, challengeRequired: false } : { ticket: 'test-only' },
        }));
        await page.routeWebSocket(/\/browser\/voice\?ticket=/, ws => {
            ws.send(JSON.stringify({ type: 'ready', protocol: 2 }));
            ws.onMessage(data => {
                if (typeof data !== 'string') return;
                const message = JSON.parse(data);
                if (message.type === 'mode' && message.mode === 'voice') ws.send(JSON.stringify({ type: 'listening_ready' }));
                if (message.type === 'end') ended = true;
            });
        });
        await page.addInitScript(() => {
            const capture = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
            navigator.mediaDevices.getUserMedia = async constraints => {
                const stream = await capture(constraints);
                (window as any).lifeTestTracks = stream.getTracks();
                return stream;
            };
        });
        await page.goto('/');
        await page.locator('[data-djinn-open]').click();
        await expect.poll(() => page.evaluate(() => (window as any).lifeTestTracks?.some((track: MediaStreamTrack) => track.readyState === 'live'))).toBe(true);
        await expect(page.locator('[data-djinn-open]')).toHaveAttribute('aria-pressed', 'true');
        // No outside pointer event: the background-mode entry itself must release capture.
        await page.locator(enter).focus();
        await page.keyboard.press('Enter');
        await expect.poll(() => page.evaluate(() => (window as any).lifeTestTracks.every((track: MediaStreamTrack) => track.readyState === 'ended'))).toBe(true);
        await expect.poll(() => ended).toBe(true);
        await expect(page.locator('[data-djinn-control]')).toHaveAttribute('data-state', 'idle');
    });
});
